title: Assignment 2
description: 
  Group 17
  <br> s205420, s242640, s250122
  <br> DTU Course 02806 social data analysis and visualization

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
